---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-sa
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-sa-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: argo-workflows-sa
    namespace: argo
roleRef:
  kind: Role
  name: argo-workflows-workflow-controller
  apiGroup: rbac.authorization.k8s.io
