---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-sa 
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-sa-binding-argo
subjects:
  - kind: ServiceAccount
    name: argo-workflows-sa
    namespace: argo
roleRef:
  kind: ClusterRole
  name: argo-workflows-sa-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-sa-binding-default
subjects:
  - kind: ServiceAccount
    name: argo-workflows-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: argo-workflows-sa-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-sa-cluster-role
rules:
  - apiGroups: ["argoproj.io"]
    resources:
      - "workflowtaskresults"
      - "workflows"
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources:
      - "pods"
      - "pods/log"
    verbs: ["get", "list", "watch"]
