---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-sa
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-sa-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: argo-workflows-sa
    namespace: argo
roleRef:
  kind: Role
  name: argo-workflows-sa-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflows-sa-role
  namespace: argo
rules:
  - apiGroups: ["argoproj.io"]
    resources:
      - "workflowtaskresults"
      - "workflows"
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources:
      - "pods"
      - "pods/log"
    verbs: ["get", "list", "watch"]
