apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-local
  namespace: argocd
spec:
  project: default
  
  source:
      repoURL: https://github.com/Matcham89/local-k8s
      targetRevision: HEAD
      path: argocd/services
  
  destination:
      server: https://kubernetes.default.svc
      namespace: default
  syncPolicy:
      syncOptions:
      - CreateNamespace=true

      automated:
        selfHeal: true
        prune: true
