apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault-local"
        vault.hashicorp.com/agent-inject-secret-config: "kv-v2/vault-local/pod-a-secret"
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "kv-v2/data/vault-local/pod-a-secret" -}}
          export SECRET_NAME="{{ .Data.data.secret_name }}"
          {{- end }}
    spec:
      serviceAccountName: vault-local
      containers:
        - name: app-a
          image: matcham89/app-a:1.0.3
          ports:
            - containerPort: 5000
          command:
            ["sh", "-c"]
          args:
            [". /vault/secrets/config && exec python app.py"]
          env:
            - name: APP_MESSAGE
              value: "Application A"
---

apiVersion: v1
kind: Service
metadata:
  name: app-a
spec:
  selector:
    app: app-a
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
