apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-k8s-sa
  namespace: argocd
spec:
  project: default
  source:
      repoURL: https://github.com/Matcham89/local-k8s.git 
      targetRevision: HEAD
      path: k8s-resources/vault-k8s-sa
  destination:
      server: https://kubernetes.default.svc
      namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
