apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  sources:
    - helm:
      chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.24.0
        valueFiles:
        - $values/helm/vault-values.yaml
    - repoURL: ' https://github.com/Matcham89/local-k8s.git '
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
