server:

  extraArgs:
    - --auth-mode=server

  ingress:
    enabled: true
    ingressClassName: "nginx"

    hosts:
      - argowf.local
    
  extraArgs:
    - --auth-mode=server


controller:
  serviceAccount:
    create: true   
    name: argo-controller-sa
  workflowNamespaces:
    - argo
clusterWorkflowTemplates:
  enabled: true
  serviceAccounts:
    name: argo-controller-sa