server:

  extraArgs:
    - --auth-mode=server

  ingress:
    enabled: true
    ingressClassName: "nginx"

    hosts:
      - argowf.local
    
  extraArgs:
    - --auth-mode=server


controller:
  workflowNamespaces:
    - argo
  serviceAccount:
    create: true   
    name: argo-controller-sa  
  rbac:
    create: true