server:
  ingress:
  # -- Enable an ingress resource
    enabled: false
    # -- Additional ingress annotations
    annotations: {}
    # -- Additional ingress labels
    labels: {}
    # -- Defines which ingress controller will implement the resource
    ingressClassName: "nginx"

    hosts:
      - argowf.local
    
  extraPaths:
    - --auth-mode=server